#all
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

# trajectory controller settings
ptp_vel: 1.0 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.5 # rad
overlap_time: 0.4
frequency: 100
operation_mode: velocity

# twist controller parameters
base_link: arm_0_link
tip_link: arm_7_link
