chains:
  - name: tray_controller
    devices:
      - name: tray_1_joint
        id: 10 
        bus: /dev/pcan32
      - name: tray_2_joint
        id: 8
        bus: /dev/pcan32
      - name: tray_3_joint
        id: 7
        bus: /dev/pcan32
