# node from which initial footprint is read
footprint_source: local_costmap_node/costmap

#
robot_base_frame: base_link
# frames to check for footprint adjustment
frames_to_check: sdh_tip_link arm_6_link arm_4_link tray_right_link tray_left_link
epsilon: 0.01
