scan_filter_chain:
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.005
    upper_threshold: 3.0
- name: intensity
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 100
    upper_threshold: 100000
    disp_histogram: 0
