port: /dev/ttyScan0
baud: 500000
scan_duration: 0.025 #no info about that in SICK-docu, but 0.025 is believable and looks good in rviz
scan_cycle_time: 0.040 #SICK-docu says S300 scans every 40ms
inverted: false # is already inverted in sick firmare configuration
scan_id: 8
frame_id: base_laser_rear_link
publish_frequency: 12
scan_intervals: [[-1.28, 1.28]] #[rad from -PI to PI] these intervals are included to the scan
