## joint_names
joint_names: [pg70_finger_left_joint]

## control_mode_adapter
max_command_silence: 0.7

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - pg70_finger_left_joint
  constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.05
      pg70_finger_left_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7


## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - pg70_finger_left_joint
  required_drive_mode: 1
     
pg70_finger_left_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: pg70_finger_left_joint
  required_drive_mode: 1

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - pg70_finger_left_joint
  required_drive_mode: 2

pg70_finger_left_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: pg70_finger_left_joint
  required_drive_mode: 2
