#all
joint_names: [torso_lower_neck_tilt_joint,torso_pan_joint,torso_upper_neck_tilt_joint]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - torso_lower_neck_tilt_joint
     - torso_pan_joint
     - torso_upper_neck_tilt_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      torso_lower_neck_tilt_joint: {trajectory: 0.1, goal: 0.1}
      torso_pan_joint: {trajectory: 0.1, goal: 0.1}
      torso_upper_neck_tilt_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7


## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - torso_lower_neck_tilt_joint
     - torso_pan_joint
     - torso_upper_neck_tilt_joint
  required_drive_mode: 1
     
torso_lower_neck_tilt_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: torso_lower_neck_tilt_joint
  required_drive_mode: 1
torso_pan_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: torso_pan_joint
  required_drive_mode: 1
torso_upper_neck_tilt_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: torso_upper_neck_tilt_joint
  required_drive_mode: 1


## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - torso_lower_neck_tilt_joint
     - torso_pan_joint
     - torso_upper_neck_tilt_joint
  required_drive_mode: 2

torso_lower_neck_tilt_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: torso_lower_neck_tilt_joint
  required_drive_mode: 2
torso_pan_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: torso_pan_joint
  required_drive_mode: 2
torso_upper_neck_tilt_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: torso_upper_neck_tilt_joint
  required_drive_mode: 2
