# canopen parameter

#schunk_powercube_chain
can_module: PCAN
can_baudrate: 1000
max_accelerations: [0.8,0.8,0.8,0.8,0.8,0.8,0.8]

OperationMode: position

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 68

#all
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
#canopen
module_ids: [4,5,6,7,8,9,10]
devices: ["/dev/pcan3", "/dev/pcan3", "/dev/pcan3", "/dev/pcan3", "/dev/pcan3", "/dev/pcan3", "/dev/pcan3"]
