#all
joint_names: [pg70_finger_left_joint]

# trajectory controller parameters
ptp_vel: 0.01 # rad/sec
ptp_acc: 0.01 # rad/sec^2
max_error: 0.15 # rad
overlap_time: 0.4
frequency: 68
operation_mode: velocity

