nodes:
  b_caster_rotation_joint:
    dcf_overlay:
      607C: '10476.25'
  fl_caster_rotation_joint:
    dcf_overlay:
      607C: '130794.0'
  fr_caster_rotation_joint:
    dcf_overlay:
      607C: '-107802.75'
