#Parameters for left drive
control_type: velocity_control
joint_name: bl_caster_rotation_joint

EncIncrPerRevMot: 4096
VelMeasFrqHz: 1
GearRatio: 15
GearEfficiency: 0.7
BeltRatio: 2
Sign: 1.0
VelMaxEncIncrS: 240000
AccIncrS: 500000
DecIncrS: 500000
Homing: false
HomePos: 0
HomeVel: 10000
HomeEvent: 9
HomeDigIn: 0x0001
HomeTimeOut: 1000
VelPModeEncIncrS: 10
CurrentContLimit: 4.4
CurrentToTorque: 1 #todo
CANId: 4

