joint_limits:
  fl_caster_rotation_joint:
    has_position_limits: false
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 2.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  fl_caster_r_wheel_joint:
    has_position_limits: false
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 2.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  fr_caster_rotation_joint:
    has_position_limits: false
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 2.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  fr_caster_r_wheel_joint:
    has_position_limits: false
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 2.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  b_caster_rotation_joint:
    has_position_limits: false
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 2.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  b_caster_r_wheel_joint:
    has_position_limits: false
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 15.0
    has_acceleration_limits: false
    max_acceleration: 2.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
