## joint_names
joint_names: [arm_shoulder_1_joint, arm_shoulder_2_joint, arm_shoulder_3_joint, arm_wrist_1_joint, arm_wrist_2_joint, arm_wrist_3_joint]

# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - arm_shoulder_1_joint
     - arm_shoulder_2_joint
     - arm_shoulder_3_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

## control_mode_adapter
max_command_silence: 0.5

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

## joint trajectory controller
joint_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - arm_shoulder_1_joint
     - arm_shoulder_2_joint
     - arm_shoulder_3_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint
   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_shoulder_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_shoulder_3_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10
   
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - arm_shoulder_1_joint
     - arm_shoulder_2_joint
     - arm_shoulder_3_joint
     - arm_wrist_1_joint
     - arm_wrist_2_joint
     - arm_wrist_3_joint

