pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      pc1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc1
        contains: 'pc1 CPU'
      pc2:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc2
        contains: 'pc2 CPU'
      pc3:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc3
        contains: 'pc3 CPU'

#  network:
#    type: diagnostic_aggregator/AnalyzerGroup
#    path: Network
#    analyzers:
#      wifi:
#        type: diagnostic_aggregator/GenericAnalyzer
#        path: wifi
#        num_items: 1
#        expected: ['Wifi Status (ddwrt)']



  io:
    type: diagnostic_aggregator/AnalyzerGroup
    path: IO
    analyzers:
      sound:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sound
        contains: 'sound'
        timeout: 15
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Joystick
        contains: 'joy'

  sensors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Sensors
    analyzers:
      laser_top:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Top
        contains: 'laser_top'
      laser_rear:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Rear
        contains: 'laser_rear'
      laser_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Front
        contains: 'laser_front'
      stereo_left:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Stereo (Left)
        contains: left
        startswith: ['stereo/left/image_color']
      stereo_right:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Stereo (Right)
        contains: right
        startswith: ['stereo/right/image_color']

  motors:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Actuators
    analyzers:
      torso:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Torso
        contains: 'torso'
      tray:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Tray
        contains: 'tray'
      gripper:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Gripper
        contains: 'gripper'
      head:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Head
        contains: 'head'
      arm:
        type: diagnostic_aggregator/GenericAnalyzer
        path: LWA
        contains: 'arm'
      base:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Base
        analyzers:
          base:
            type: diagnostic_aggregator/GenericAnalyzer
            path: drives
            startswith: '/base'
          base_twist_mux:
            type: diagnostic_aggregator/GenericAnalyzer
            path: twist_mux
            contains: 'twist_mux'
