can_module: PCAN
can_device: /dev/pcan2
can_baudrate: 1000
modul_ids: [4,5,6,7,8,9,10]
module_types: [PW,PW,PW,PW,PW,PW,PW]
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
max_accelerations: [0.8,0.8,0.8,0.8,0.8,0.8,0.8]
min_publish_duration: 0.1
horizon: 0.1
OperationMode: position

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.1 # rad
frequency: 50
