#raw-mini
##########
# common params
run_factor: 2.0
apply_ramp: false
joy_num_buttons: 12
joy_num_axes: 6
joy_num_modes: 1

# axes
axis_vx: 4
axis_vy: 3
axis_vz: 5
axis_roll: 4
axis_pitch: 3
axis_yaw: 0

# buttons
deadman_button: 5
safety_button: 6
init_button: 9

#mode1: Base
run_button: 7

components: {
  base: {
    twist_topic_name: '/base/twist_mux/command_teleop_joy',
    twist_safety_topic_name: '/base/twist_mux/command_teleop_joy',
    twist_max_velocity: [0.5, 0.5, 0.5],
    twist_max_acc: [0.5, 0.5, 0.7]
  }
}
