
# TODO: Could be moved to plt.yaml - should be revolved with mig
SteerCtrl:

  # Parameters for tuning Impedance-Controller
  Spring: 15.0 #10.0
  Damp: 2.75 #2.5
  VirtMass: 0.1 #0.1
  DPhiMax: 10.0 #12.0
  DDPhiMax: 40.0 #100.0
