---
Config:

  # cpc-pk: This is necessary to have configurations like COB3_5 with less wheels
  NumberOfMotors: 8
  NumberOfWheels: 4

Geom:
  # Radius of the wheels in [mm]
  RadiusWheeL: 80

  # Distance of the wheels steering axis to the wheel center in [mm]
  DistSteerAxisToDriveWheelCenter: 0 #22

  Wheels:
    0:
      xPos: 368
      yPos: 186
      WheelSteerDriveCoupling: 0.0
      WheelNeutralPosition: -180.0
    1:
      xPos: -368
      yPos: 134
      WheelSteerDriveCoupling: 0.0
      WheelNeutralPosition: -180.0
    2:
      xPos: -368
      yPos: -186
      WheelSteerDriveCoupling: 0.0
      WheelNeutralPosition: 0.0
    3:
      xPos: 368
      yPos: -134
      WheelSteerDriveCoupling: 0.0
      WheelNeutralPosition: 0.0

DrivePrms:
  # Maximum Rotational Rate for the Drive Wheels [rad/s]
  MaxDriveRate: 12.267

  # Maximum Rotational Rate for Steering Motion of the wheels [rad/s]
  MaxSteerRate: 24.4


...

