
# platform specific configuration params
Config:
  NumberOfMotors: 8
  NumberOfWheels: 4

# Multi threading params
Thread:
  # used as command rate (dCmdRateS)
  ThrUCarrCycleTimeS: 0.02   #0.0

# platform specific geometrics
Geom:
  # TODO: Could be added per wheel - should be revolved with mig
  # Radius of the wheels in [mm]
  RadiusWheeL: 80

  # TODO: Could be added per wheel - should be revolved with mig
  # Distance of the wheels steering axis to the wheel center in [mm]
  DistSteerAxisToDriveWheelCenter: 0 #22

  # wheel configuration
  # labeling: start front left, clockwise with x-axis
  Wheels:
      - xPos: 368.0
        yPos: 186.0
        SteerDriveCoupling: 0.0
        NeutralPosition: -180.0

        # Maximum Rotational Rate for the Drive Wheels [rad/s]
        MaxDriveRate: 12.267
        # Maximum Rotational Rate for Steering Motion of the wheels [rad/s]
        MaxSteerRate: 24.4

      - xPos: -368.0
        yPos: 134.0
        SteerDriveCoupling: 0.0
        NeutralPosition: -180.0

        # Maximum Rotational Rate for the Drive Wheels [rad/s]
        MaxDriveRate: 12.267
        # Maximum Rotational Rate for Steering Motion of the wheels [rad/s]
        MaxSteerRate: 24.4

      - xPos: -368.0
        yPos: -186.0
        SteerDriveCoupling: 0.0
        NeutralPosition: 0.0

        # Maximum Rotational Rate for the Drive Wheels [rad/s]
        MaxDriveRate: 12.267
        # Maximum Rotational Rate for Steering Motion of the wheels [rad/s]
        MaxSteerRate: 24.4

      - xPos: 368.0
        yPos: -134.0
        SteerDriveCoupling: 0.0
        NeutralPosition: 0.0

        # Maximum Rotational Rate for the Drive Wheels [rad/s]
        MaxDriveRate: 12.267
        # Maximum Rotational Rate for Steering Motion of the wheels [rad/s]
        MaxSteerRate: 24.4

SteerCtrl:

  # Parameters for tuning Impedance-Controller
  Spring: 15.0 #10.0
  Damp: 2.75 #2.5
  VirtMass: 0.1 #0.1
  DPhiMax: 10.0 #12.0
  DDPhiMax: 40.0 #100.0

