nodes:
  ##Wheel 1
  fw_steer_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-51776"# home offset

  ##Wheel 2
  bw_steer_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-173177" # home offset

  ##Wheel 3

