joint_names: [gripper_right_finger_left_joint]
action_name: /gripper_right/joint_trajectory_controller/follow_joint_trajectory
service_ns: /gripper_right/driver
default_acc: 0.3
default_vel: 0.01

home: [[0.02]]
close: [[0.00]]
open: [[0.03]]
