joint_names: [gripper_left_finger_left_joint]
action_name: /gripper_left/joint_trajectory_controller/follow_joint_trajectory
service_ns: /gripper_left/driver
default_acc: 0.3
default_vel: 0.01

home: [[0.02]]
close: [[0.00]]
open: [[0.03]]
