<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find cob_hardware_config)/raw3-3/urdf/calibration_default.urdf.xacro" />
	<xacro:include filename="$(find cob_calibration_data)/raw3-3/calibration/calibration_offset.urdf.xacro" />>

	<!-- *********************** -->
	<!-- upper robot calibration -->
	<!-- *********************** -->
	<!-- tower mount positions | relative to base_link -->
	<property name="tower_x" value="${def_tower_x+offset_tower_x}"/>
	<property name="tower_y" value="${def_tower_y+offset_tower_y}"/>
	<property name="tower_z" value="${def_tower_z+offset_tower_z}"/>
	<property name="tower_roll" value="${def_tower_roll+offset_tower_roll}"/>
	<property name="tower_pitch" value="${def_tower_pitch+offset_tower_pitch}"/>
	<property name="tower_yaw" value="${def_tower_yaw+offset_tower_yaw}"/>

	<!-- arm mount positions | relative to base_link -->
	<property name="arm_x" value="${def_arm_x+offset_arm_x}"/>
	<property name="arm_y" value="${def_arm_y+offset_arm_y}"/>
	<property name="arm_z" value="${def_arm_z+offset_arm_z}"/>
	<property name="arm_roll" value="${def_arm_roll+offset_arm_roll}"/>
	<property name="arm_pitch" value="${def_arm_pitch+offset_arm_pitch}"/>
	<property name="arm_yaw" value="${def_arm_yaw+offset_arm_yaw}"/>

	<!-- gripper_left mount positions | relative to arm_left_7_link -->
	<property name="gripper_left_x" value="${def_gripper_left_x+offset_gripper_left_x}"/>
	<property name="gripper_left_y" value="${def_gripper_left_y+offset_gripper_left_y}"/>
	<property name="gripper_left_z" value="${def_gripper_left_z+offset_gripper_left_z}"/>
	<property name="gripper_left_roll" value="${def_gripper_left_roll+offset_gripper_left_roll}"/>
	<property name="gripper_left_pitch" value="${def_gripper_left_pitch+offset_gripper_left_pitch}"/>
	<property name="gripper_left_yaw" value="${def_gripper_left_yaw+offset_gripper_left_yaw}"/>

	<!-- gripper_right mount positions | relative to arm_right_7_link -->
	<property name="gripper_right_x" value="${def_gripper_right_x+offset_gripper_right_x}"/>
	<property name="gripper_right_y" value="${def_gripper_right_y+offset_gripper_right_y}"/>
	<property name="gripper_right_z" value="${def_gripper_right_z+offset_gripper_right_z}"/>
	<property name="gripper_right_roll" value="${def_gripper_right_roll+offset_gripper_right_roll}"/>
	<property name="gripper_right_pitch" value="${def_gripper_right_pitch+offset_gripper_right_pitch}"/>
	<property name="gripper_right_yaw" value="${def_gripper_right_yaw+offset_gripper_right_yaw}"/>

	<!-- neck mount positions | relative to arm_torso_link -->
	<property name="neck_x" value="${def_neck_x+offset_neck_x}"/>
	<property name="neck_y" value="${def_neck_y+offset_neck_y}"/>
	<property name="neck_z" value="${def_neck_z+offset_neck_z}"/>
	<property name="neck_roll" value="${def_neck_roll+offset_neck_roll}"/>
	<property name="neck_pitch" value="${def_neck_pitch+offset_neck_pitch}"/>
	<property name="neck_yaw" value="${def_neck_yaw+offset_neck_yaw}"/>

	<!-- head mount positions | relative to neck_mount_link -->
	<property name="head_x" value="${def_head_x+offset_head_x}"/>
	<property name="head_y" value="${def_head_y+offset_head_y}"/>
	<property name="head_z" value="${def_head_z+offset_head_z}"/>
	<property name="head_roll" value="${def_head_roll+offset_head_roll}"/>
	<property name="head_pitch" value="${def_head_pitch+offset_head_pitch}"/>
	<property name="head_yaw" value="${def_head_yaw+offset_head_yaw}"/>

	<!-- ids_middle mount positions | relative to head_cam_holder_link -->
	<property name="ids_middle_x" value="${def_ids_middle_x+offset_ids_middle_x}"/>
	<property name="ids_middle_y" value="${def_ids_middle_y+offset_ids_middle_y}"/>
	<property name="ids_middle_z" value="${def_ids_middle_z+offset_ids_middle_z}"/>
	<property name="ids_middle_roll" value="${def_ids_middle_roll+offset_ids_middle_roll}"/>
	<property name="ids_middle_pitch" value="${def_ids_middle_pitch+offset_ids_middle_pitch}"/>
	<property name="ids_middle_yaw" value="${def_ids_middle_yaw+offset_ids_middle_yaw}"/>

	<!-- ids_left mount positions | relative to head_cam_holder_link -->
	<property name="ids_left_x" value="${def_ids_left_x+offset_ids_left_x}"/>
	<property name="ids_left_y" value="${def_ids_left_y+offset_ids_left_y}"/>
	<property name="ids_left_z" value="${def_ids_left_z+offset_ids_left_z}"/>
	<property name="ids_left_roll" value="${def_ids_left_roll+offset_ids_left_roll}"/>
	<property name="ids_left_pitch" value="${def_ids_left_pitch+offset_ids_left_pitch}"/>
	<property name="ids_left_yaw" value="${def_ids_left_yaw+offset_ids_left_yaw}"/>

	<!-- ids_right mount positions | relative to head_cam_holder_link -->
	<property name="ids_right_x" value="${def_ids_right_x+offset_ids_right_x}"/>
	<property name="ids_right_y" value="${def_ids_right_y+offset_ids_right_y}"/>
	<property name="ids_right_z" value="${def_ids_right_z+offset_ids_right_z}"/>
	<property name="ids_right_roll" value="${def_ids_right_roll+offset_ids_right_roll}"/>
	<property name="ids_right_pitch" value="${def_ids_right_pitch+offset_ids_right_pitch}"/>
	<property name="ids_right_yaw" value="${def_ids_right_yaw+offset_ids_right_yaw}"/>

	<!-- cam_holder mount positions | relative to head_powerball_knob_link -->
	<property name="cam_holder_x" value="${def_cam_holder_x+offset_cam_holder_x}"/>
	<property name="cam_holder_y" value="${def_cam_holder_y+offset_cam_holder_y}"/>
	<property name="cam_holder_z" value="${def_cam_holder_z+offset_cam_holder_z}"/>
	<property name="cam_holder_roll" value="${def_cam_holder_roll+offset_cam_holder_roll}"/>
	<property name="cam_holder_pitch" value="${def_cam_holder_pitch+offset_cam_holder_pitch}"/>
	<property name="cam_holder_yaw" value="${def_cam_holder_yaw+offset_cam_holder_yaw}"/>
	
	<property name="torso_bottom_ref" value="${def_torso_bottom_ref+offset_torso_bottom_ref}"/>
	<property name="torso_side_ref" value="${def_torso_side_ref+offset_torso_side_ref}"/>

	<!-- laser mount positions | relative to base_link -->
	<property name="laser_front_x" value="${def_laser_front_x+offset_laser_front_x}"/>
	<property name="laser_rear_x" value="${def_laser_rear_x+offset_laser_rear_x}"/>
	<property name="laser_front_y" value="${def_laser_front_y+offset_laser_front_y}"/>
	<property name="laser_rear_y" value="${def_laser_rear_y+offset_laser_rear_y}"/>
	<property name="laser_front_yaw" value="${def_laser_front_yaw+offset_laser_front_yaw}"/>
	<property name="laser_rear_yaw" value="${def_laser_rear_yaw+offset_laser_rear_yaw}"/>

</robot>
