nodes:
  fl_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "127621.5" # home offset

  b_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "9528.0" #  home offset

  fr_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-108166.0" # home offset
