joint_names: [torso_2_joint, torso_3_joint]
action_name: /torso/joint_trajectory_controller/follow_joint_trajectory
service_ns: /torso/driver
default_vel: 0.4

home: [[0.0,0.0]]

front: [[0.0, 0.0]]
front_up: [[1.0, -0.5]]
front_up_full: [[3.14, -1.57]]
front_down: [[-1.0, 0.5]]
front_down_full: [[-3.14, 1.57]]

back: [back_left]
back_left: [[0.0, 3.14]]
back_right: [[0.0, -3.14]]
back_up: [[-1.0, 3.64]]
back_up_full: [[-3.14, 4.71]]
back_down: [[1.0, 2.34]]
back_down_full: [[3.14, 1.57]]

left: [[0.0, 1.57]]
right: [[0.0, -1.57]]

nod: [front_down, front]
shake: [left, right, left, home]
