<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find cob_hardware_config)/cob3-8/urdf/calibration_default.urdf.xacro" />
	<xacro:include filename="$(find cob_calibration_data)/cob3-8/calibration/calibration_offset.urdf.xacro" />
	<!-- ***************** -->
	<!-- base calibration -->
	<!-- ***************** -->
	<!-- laser front mount positions | relative to base_link -->
	<property name="laser_front_x" value="${def_laser_front_x+offset_laser_front_x}"/>
	<property name="laser_front_y" value="${def_laser_front_y+offset_laser_front_y}"/>
	<property name="laser_front_z" value="${def_laser_front_z+offset_laser_front_z}"/>
	<property name="laser_front_roll" value="${def_laser_front_roll+offset_laser_front_roll}"/>
	<property name="laser_front_pitch" value="${def_laser_front_pitch+offset_laser_front_pitch}"/>
	<property name="laser_front_yaw" value="${def_laser_front_yaw+offset_laser_front_yaw}"/>

	<!-- laser rear mount positions | relative to base_link -->
	<property name="laser_rear_x" value="${def_laser_rear_x+offset_laser_rear_x}"/>
	<property name="laser_rear_y" value="${def_laser_rear_y+offset_laser_rear_y}"/>
	<property name="laser_rear_z" value="${def_laser_rear_z+offset_laser_rear_z}"/>
	<property name="laser_rear_roll" value="${def_laser_rear_roll+offset_laser_rear_roll}"/>
	<property name="laser_rear_pitch" value="${def_laser_rear_pitch+offset_laser_rear_pitch}"/>
	<property name="laser_rear_yaw" value="${def_laser_rear_yaw+offset_laser_rear_yaw}"/>

	<!-- laser top mount positions | relative to base_link -->
	<property name="laser_top_x" value="${def_laser_top_x+offset_laser_top_x}"/>
	<property name="laser_top_y" value="${def_laser_top_y+offset_laser_top_y}"/>
	<property name="laser_top_z" value="${def_laser_top_z+offset_laser_top_z}"/>
	<property name="laser_top_roll" value="${def_laser_top_roll+offset_laser_top_roll}"/>
	<property name="laser_top_pitch" value="${def_laser_top_pitch+offset_laser_top_pitch}"/>
	<property name="laser_top_yaw" value="${def_laser_top_yaw+offset_laser_top_yaw}"/>

	<!-- *********************** -->
	<!-- upper robot calibration -->
	<!-- *********************** -->
	<!-- tray mount positions | relative to base_link -->
	<property name="tray_x" value="${def_tray_x+offset_tray_x}"/>
	<property name="tray_y" value="${def_tray_y+offset_tray_y}"/>
	<property name="tray_z" value="${def_tray_z+offset_tray_z}"/>
	<property name="tray_roll" value="${def_tray_roll+offset_tray_roll}"/>
	<property name="tray_pitch" value="${def_tray_pitch+offset_tray_pitch}"/>
	<property name="tray_yaw" value="${def_tray_yaw+offset_tray_yaw}"/>

	<!-- torso mount positions | relative to base_link -->
	<property name="torso_x" value="${def_torso_x+offset_torso_x}"/>
	<property name="torso_y" value="${def_torso_y+offset_torso_y}"/>
	<property name="torso_z" value="${def_torso_z+offset_torso_z}"/>
	<property name="torso_roll" value="${def_torso_roll+offset_torso_roll}"/>
	<property name="torso_pitch" value="${def_torso_pitch+offset_torso_pitch}"/>
	<property name="torso_yaw" value="${def_torso_yaw+offset_torso_yaw}"/>

	<!-- head mount positions | relative to head_cover_link -->
	<property name="head_x" value="${def_head_x+offset_head_x}"/>
	<property name="head_y" value="${def_head_y+offset_head_y}"/>
	<property name="head_z" value="${def_head_z+offset_head_z}"/>
	<property name="head_roll" value="${def_head_roll+offset_head_roll}"/>
	<property name="head_pitch" value="${def_head_pitch+offset_head_pitch}"/>
	<property name="head_yaw" value="${def_head_yaw+offset_head_yaw}"/>

	<!-- arm mount positions | relative to base_link -->
	<property name="arm_x" value="${def_arm_x+offset_arm_x}"/>
	<property name="arm_y" value="${def_arm_y+offset_arm_y}"/>
	<property name="arm_z" value="${def_arm_z+offset_arm_z}"/>
	<property name="arm_roll" value="${def_arm_roll+offset_arm_roll}"/>
	<property name="arm_pitch" value="${def_arm_pitch+offset_arm_pitch}"/>
	<property name="arm_yaw" value="${def_arm_yaw+offset_arm_yaw}"/>
	
	<!-- pg70 mount positions | relative to arm_7_link -->
	<property name="pg70_x" value="${def_pg70_x+offset_pg70_x}"/>
	<property name="pg70_y" value="${def_pg70_y+offset_pg70_y}"/>
	<property name="pg70_z" value="${def_pg70_z+offset_pg70_z}"/>
	<property name="pg70_roll" value="${def_pg70_roll+offset_pg70_roll}"/>
	<property name="pg70_pitch" value="${def_pg70_pitch+offset_pg70_pitch}"/>
	<property name="pg70_yaw" value="${def_pg70_yaw+offset_pg70_yaw}"/>

	<!-- *********************************** -->
	<!-- kinematic chain reference positions -->
	<!-- *********************************** -->
	<!-- torso chain calibration_offest! | relative to reference position (see below)-->

	<!-- torso reference positions | used as calibration_rising for torso chain -->
	<!-- ! set these values to make torso straight with (0, 0, 0) joint angles ! -->
	<property name="torso_lower_neck_tilt_ref" value="${def_torso_lower_neck_tilt_ref+offset_torso_lower_neck_tilt_ref}"/>
	<property name="torso_pan_ref" value="${def_torso_pan_ref+offset_torso_pan_ref}"/>
	<property name="torso_upper_neck_tilt_ref" value="${def_torso_upper_neck_tilt_ref+offset_torso_upper_neck_tilt_ref}"/>

	<!-- tray reference position | used as calibration_rising for tray chain -->
	<property name="tray_ref" value="${def_tray_ref+offset_tray_ref}"/>

	<!-- head camera axis reference position | used as calibration_rising for head axis chain -->
	<property name="head_axis_ref" value="${def_head_axis_ref+offset_head_axis_ref}"/>

	<!-- arm reference positions | used as calibration_rising for arm chain-->
	<property name="arm_1_ref" value="${def_arm_1_ref+offset_arm_1_ref}"/>
	<property name="arm_2_ref" value="${def_arm_2_ref+offset_arm_2_ref}"/>
	<property name="arm_3_ref" value="${def_arm_3_ref+offset_arm_3_ref}"/>
	<property name="arm_4_ref" value="${def_arm_4_ref+offset_arm_4_ref}"/>
	<property name="arm_5_ref" value="${def_arm_5_ref+offset_arm_5_ref}"/>
	<property name="arm_6_ref" value="${def_arm_6_ref+offset_arm_6_ref}"/>
	<property name="arm_7_ref" value="${def_arm_7_ref+offset_arm_7_ref}"/>

	<!-- gripper reference positions | used as calibration_rising for gripper chain-->
	<property name="pg70_finger_left_ref" value="${def_pg70_finger_left_ref+offset_pg70_finger_left_ref}"/>
	<property name="pg70_finger_right_ref" value="${def_pg70_finger_right_ref+offset_pg70_finger_right_ref}"/>


	<!-- ***************************** -->
	<!-- camera calibration properties -->
	<!-- ***************************** -->
	<!-- left | handeye calibration | relative to head_axis_link -->
	<property name="cam_reference_x" value="${def_cam_reference_x+offset_cam_reference_x}"/>
	<property name="cam_reference_y" value="${def_cam_reference_y+offset_cam_reference_y}"/>
	<property name="cam_reference_z" value="${def_cam_reference_z+offset_cam_reference_z}"/>
	<property name="cam_reference_roll" value="${def_cam_reference_roll+offset_cam_reference_roll}"/>
	<property name="cam_reference_pitch" value="${def_cam_reference_pitch+offset_cam_reference_pitch}"/>
	<property name="cam_reference_yaw" value="${def_cam_reference_yaw+offset_cam_reference_yaw}"/>
	
	<!-- cam3d | handeye calibration | relative to cam_reference_link -->
	<property name="cam3d_x" value="${def_cam3d_x+offset_cam3d_x}"/>
	<property name="cam3d_y" value="${def_cam3d_y+offset_cam3d_y}"/>
	<property name="cam3d_z" value="${def_cam3d_z+offset_cam3d_z}"/>
	<property name="cam3d_roll" value="${def_cam3d_roll+offset_cam3d_roll}"/>
	<property name="cam3d_pitch" value="${def_cam3d_pitch+offset_cam3d_pitch}"/>
	<property name="cam3d_yaw" value="${def_cam3d_yaw+offset_cam3d_yaw}"/>
</robot>
