# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

# Mandatory parameters
speed_lim_vx: 1.2
speed_lim_vy: 1.0
speed_lim_w: 1.2

accel_lim_vx: 0.5
accel_lim_vy: 0.5
accel_lim_w: 0.5

# Optional parameters
frequency: 50.0
decel_factor: 1.5       #used if zero velocity is received or goal velocity is far away from current velocity
decel_factor_safe: 2.5  #used if no velocity commands received (eg. no deadman on joystick)

# Robot velocity feedback type:
#  0 - none
#  1 - odometry
#  2 - end robot commands
robot_feedback: 1
