nodes:
  fl_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "129950.0" # home offset

  b_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "7649.5" # home offset

  fr_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-109273.5" # home offset
