controller_list:
  - name: fake_arm_left_controller
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: fake_arm_right_controller
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: fake_gripper_left_controller
    joints:
      - gripper_left_finger_1_joint
      - gripper_left_finger_2_joint
  - name: fake_gripper_right_controller
    joints:
      - gripper_right_finger_1_joint
      - gripper_right_finger_2_joint
  - name: fake_torso_controller
    joints:
      - torso_2_joint
      - torso_3_joint
