sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /torso_cam3d_down/depth_registered/points
    max_range: 4.0
    point_subsample: 1
    shape_padding: 0.05
    shape_scale: 1.0
  #- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    #point_cloud_topic: /torso_cam3d_left/depth_registered/points
    #max_range: 4.0
    #point_subsample: 1
    #shape_padding: 0.05
    #shape_scale: 1.0
  #- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    #point_cloud_topic: /torso_cam3d_right/depth_registered/points
    #max_range: 4.0
    #point_subsample: 1
    #shape_padding: 0.05
    #shape_scale: 1.0
  #- sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    #point_cloud_topic: /sensorring_cam3d/depth_registered/points
    #max_range: 4.0
    #point_subsample: 1
    #shape_padding: 0.05
    #shape_scale: 1.0
