device: /dev/pcan3
baudrate: 500K
sync_interval: 10
chains: ["arm_left_controller"]
arm_left_controller:
  joint_names: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint]
  motor_direction: [1, 1, 1]
  module_ids: [61, 62, 63]
