device: /dev/pcan0
baudrate: 500K
sync_interval: 5
chains: ["torso_controller"]
torso_controller:
  joint_names: [torso_1_joint,torso_2_joint,torso_3_joint]
  motor_direction: [1, 1, 1]
  module_ids: [30,31,32]
