ip_address: "192.168.21.102"
#guid: "106632"
auto_exposure:     True
exposure_auto_max: 100000
exposure_auto_target: 40
exposure:          0.009
auto_gain:         True
gain_auto_target: 40
gain:              1
auto_whitebalance: True
frame_id: head_color_camera_l_link
stream_bytes_per_second: 17500000   # full speed in stereo rig: 55000000
auto_adjust_stream_bytes_per_second: False
trigger_mode: syncin1
packet_size: 9000
trig_rate: 1
