# powercube_chain parameters
can_module: PCAN
can_device: /dev/pcan1
can_baudrate: 1000
modul_ids: [1,2,3]
joint_names: [torso_lower_neck_tilt_joint, torso_pan_joint, torso_upper_neck_tilt_joint]
max_accelerations: [0.8,0.8,0.8]
min_publish_duration: 0.1
horizon: 0.05 # [s]
frequency: 100

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
