<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:include filename="$(find cob_hardware_config)/raw3-4/urdf/calibration_default.urdf.xacro" />
	<xacro:include filename="$(find cob_calibration_data)/raw3-4/calibration/calibration_offset.urdf.xacro" />

	<!-- tower mount positions | relative to base_link -->
	<property name="tower_x" value="${def_tower_x+offset_tower_x}"/>
	<property name="tower_y" value="${def_tower_y+offset_tower_y}"/>
	<property name="tower_z" value="${def_tower_z+offset_tower_z}"/>
	<property name="tower_roll" value="${def_tower_roll+offset_tower_roll}"/>
	<property name="tower_pitch" value="${def_tower_pitch+offset_tower_pitch}"/>
	<property name="tower_yaw" value="${def_tower_yaw+offset_tower_yaw}"/>

	<!-- arm mount positions | relative to base_link -->
	<property name="arm_x" value="${def_arm_x+offset_arm_x}"/>
	<property name="arm_y" value="${def_arm_y+offset_arm_y}"/>
	<property name="arm_z" value="${def_arm_z+offset_arm_z}"/>
	<property name="arm_roll" value="${def_arm_roll+offset_arm_roll}"/>
	<property name="arm_pitch" value="${def_arm_pitch+offset_arm_pitch}"/>
	<property name="arm_yaw" value="${def_arm_yaw+offset_arm_yaw}"/>

</robot>
