defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-2/config/Elmo.dcf"
  dcf_overlay:
    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127

nodes:
  - name: torso_2_joint
    id: 32
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6083": "6000" # profile acceleration, mgrad/sec^2
      "6084": "6000" # profile deceleration, mgrad/sec^2
      "60C5": "6000" # max acceleration, mgrad/sec^2
      "60C6": "6000" # max deceleration, mgrad/sec^2
  - name: torso_3_joint
    id: 33
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6083": "80000" # profile acceleration, mgrad/sec^2
      "6084": "80000" # profile deceleration, mgrad/sec^2
      "60C5": "80000" # max acceleration, mgrad/sec^2
      "60C6": "80000" # max deceleration, mgrad/sec^2
