pub_rate: 1.0 # Optional
base_path: '' # Optional, prepended to all diagnostic output
analyzers:
  computers:
    type: AnalyzerGroup
    path: Computers
    analyzers:
      pc1:
        type: diagnostic_aggregator/GenericAnalyzer
        path: pc1
        contains: 'pc1'

  sensors:
    type: AnalyzerGroup
    path: Sensors
    analyzers:
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Joystick
        contains: 'joy'
      laser_rear:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Rear
        contains: 'laser_rear'
      laser_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Scan Front
        contains: 'laser_front'

  motors:
    type: AnalyzerGroup
    path: Actuators
    analyzers:
      base:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base
        contains: 'base_controller'
