joint_names: ["torso_lower_neck_tilt_joint","torso_pan_joint","torso_upper_neck_tilt_joint"]
action_name: torso/joint_trajectory_controller/follow_joint_trajectory
service_ns: torso/driver
default_vel: 0.1

home: [[0.0,0.0,0.0]]
left: [[0.0,-0.1,0.0]]
right: [[0.0,0.1,0.0]]
front: [[-0.1,0.0,-0.15]]
front_extreme: [[-0.2,0.0,-0.35]]
front_left: [[-0.1,-0.1,-0.15]]
front_left_extreme: [[-0.2,-0.1,-0.35]]
front_right: [[-0.1,0.1,-0.15]]
front_right_extreme: [[-0.2,0.1,-0.35]]
back: [[0.1,0.0,0.15]]
back_extreme: [[0.20,0.0,0.35]]
back_left: [[0.1,-0.1,0.15]]
back_left_extreme: [[0.20,-0.1,0.35]]
back_right: [[0.1,0.1,0.15]]
back_right_extreme: [[0.20,0.1,0.35]]
nod: [front,home]
bow: [front_extreme, front_extreme, home]
shake: [left, right, left, home]
