joint_limits:
  fl_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    #has_acceleration_limits: false
    #max_acceleration: 2.0
  fl_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    #has_acceleration_limits: false
    #max_acceleration: 2.0
  fr_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    #has_acceleration_limits: false
    #max_acceleration: 2.0
  fr_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    #has_acceleration_limits: false
    #max_acceleration: 2.0
  b_caster_rotation_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    #has_acceleration_limits: false
    #max_acceleration: 2.0
  b_caster_r_wheel_joint:
    has_velocity_limits: true
    max_velocity: 15.0
    #has_acceleration_limits: false
    #max_acceleration: 2.0
