battery_max_voltage: 50
battery_min_voltage: 44
robot_max_voltage: 60 # Maximal possible voltage when measurement voltage is 5V
phidget_max_counts: 1024 # Maximal possible counts when 5V voltage is on input (10 bit resolution)