# global information
global_frame: base_link
robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 5.0
map_type: costmap

# local map settings
static_map: false
rolling_window: true
width: 5.0
height: 5.0
resolution: 0.07

# footprint and range
obstacle_range: 3.0 #[m]
max_obstacle_height: 2.0 #[m]
raytrace_range: 3.0 #3.0 #[m]
footprint: [[0.55, 0.3], [0.55, -0.3], [-0.55, -0.3],[-0.55, 0.3]] #[m]
footprint_padding: 0.15 #[m]
inflation_radius: 0.55 #[m]

# sensor setup
observation_sources: laser_scan_sensor_front laser_scan_sensor_rear
laser_scan_sensor_front: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: laser_front/scan_filtered, marking: true, clearing: true}

laser_scan_sensor_rear: {sensor_frame: base_laser_rear_link, data_type: LaserScan, topic: laser_rear/scan_filtered, marking: true, clearing: true}


